AWSTemplateFormatVersion: '2010-09-09'


Description: 'CloudFormation template for a resource'

Resources:
  MyResource:
    Type: AWS::S3::Bucket


  MyResource2:
    Type: AWS::S3::Bucket


  MyResource3:
    Type: AWS::S3::Bucket